// <auto-generated />
using IPTOffering.Repository.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IPTOffering.Repository.Migrations
{
    [DbContext(typeof(IPTOContext))]
    [Migration("20211119062032_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("IPTOffering.Repository.Models.IPTreatmentPackage", b =>
                {
                    b.Property<int>("IPTreatmentPackagesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ailment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PackageId")
                        .HasColumnType("int");

                    b.HasKey("IPTreatmentPackagesId");

                    b.HasIndex("PackageId");

                    b.ToTable("IPTreatmentPackage");
                });

            modelBuilder.Entity("IPTOffering.Repository.Models.PackageDetail", b =>
                {
                    b.Property<int>("PackageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TestDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TreatmentDuration")
                        .HasColumnType("int");

                    b.Property<string>("TreatmentPackageName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PackageId");

                    b.ToTable("PackageDetail");
                });

            modelBuilder.Entity("IPTOffering.Repository.Models.SpecialistDetail", b =>
                {
                    b.Property<int>("SpecialistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AreaOfExpertise")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ExperienceInYears")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TreatmentDuration")
                        .HasColumnType("int");

                    b.HasKey("SpecialistId");

                    b.ToTable("SpecialistDetails");
                });

            modelBuilder.Entity("IPTOffering.Repository.Models.IPTreatmentPackage", b =>
                {
                    b.HasOne("IPTOffering.Repository.Models.PackageDetail", "PackageDetail")
                        .WithMany("IPTreatmentPackages")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PackageDetail");
                });

            modelBuilder.Entity("IPTOffering.Repository.Models.PackageDetail", b =>
                {
                    b.Navigation("IPTreatmentPackages");
                });
#pragma warning restore 612, 618
        }
    }
}
